### ISSUE TITLE
AWS Profile Could Not Be Found

### ISSUE THREAD

**Issue by SoundsSerious** [MacHu-GWU/pysecret-project#2]
Hi, Nice library!

Few issues setting up AWS, that aren't super clear what the solution is.

On initalizing the first aws example
```ProfileNotFound: The config profile (my_aws_profile) could not be found```

Additonally i got a silent error on importing `AWSSecret` without boto3 installed, would suggest that a warning is added.

**Comment by MacHu-GWU** [comment]
@SoundsSerious Hi, could you attach some code about how you reproduce this error? And could you also post your OS (windows / Mac / Linux) and Python version (2.7 / 3.4 / 3.5 / ... / 3.9) you are using?

**Comment by SoundsSerious** [comment]
Hi,

This appears to be an AWS credentials issue as well. I reconfigured my env and it appears to be working.
